// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.0
// source: api/specs/specs.proto

package specs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Schematic    string                 `protobuf:"bytes,1,opt,name=schematic,proto3" json:"schematic,omitempty"`
	TalosVersion string                 `protobuf:"bytes,2,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	// architecture is "x86" or "arm", resolved from server_type.
	Architecture string `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// image_id is the Hetzner snapshot Image ID, cached/shared across machines
	// built from the same schematic/talos_version/architecture.
	ImageId        int64   `protobuf:"varint,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ServerId       int64   `protobuf:"varint,5,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreateActionId int64   `protobuf:"varint,6,opt,name=create_action_id,json=createActionId,proto3" json:"create_action_id,omitempty"`
	VolumeIds      []int64 `protobuf:"varint,7,rep,packed,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_api_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_api_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetSchematic() string {
	if x != nil {
		return x.Schematic
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *MachineSpec) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *MachineSpec) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *MachineSpec) GetCreateActionId() int64 {
	if x != nil {
		return x.CreateActionId
	}
	return 0
}

func (x *MachineSpec) GetVolumeIds() []int64 {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

var File_api_specs_specs_proto protoreflect.FileDescriptor

const file_api_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x15api/specs/specs.proto\x12\fhetznerspecs\"\xf5\x01\n" +
	"\vMachineSpec\x12\x1c\n" +
	"\tschematic\x18\x01 \x01(\tR\tschematic\x12#\n" +
	"\rtalos_version\x18\x02 \x01(\tR\ftalosVersion\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\x03R\aimageId\x12\x1b\n" +
	"\tserver_id\x18\x05 \x01(\x03R\bserverId\x12(\n" +
	"\x10create_action_id\x18\x06 \x01(\x03R\x0ecreateActionId\x12\x1d\n" +
	"\n" +
	"volume_ids\x18\a \x03(\x03R\tvolumeIdsB9Z7github.com/coolguy1771/hetzner-infra-provider/api/specsb\x06proto3"

var (
	file_api_specs_specs_proto_rawDescOnce sync.Once
	file_api_specs_specs_proto_rawDescData []byte
)

func file_api_specs_specs_proto_rawDescGZIP() []byte {
	file_api_specs_specs_proto_rawDescOnce.Do(func() {
		file_api_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)))
	})
	return file_api_specs_specs_proto_rawDescData
}

var file_api_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: hetznerspecs.MachineSpec
}
var file_api_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_specs_specs_proto_init() }
func file_api_specs_specs_proto_init() {
	if File_api_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_specs_specs_proto_goTypes,
		DependencyIndexes: file_api_specs_specs_proto_depIdxs,
		MessageInfos:      file_api_specs_specs_proto_msgTypes,
	}.Build()
	File_api_specs_specs_proto = out.File
	file_api_specs_specs_proto_goTypes = nil
	file_api_specs_specs_proto_depIdxs = nil
}
